[[h4]]
class = "rasp_day_mobile"
text = "Понедельник"

[[div]]
class = "rasp_tabl_day"

  [div.table]
  id = "3day"
  class = "rasp_tabl"
  border = "0"
  cellpadding = "0"
  cellspacing = "0"

    [div.table.tbody]
      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"
          [div.table.tbody.tr.th.span]
          text = "Пн"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>11:30-13:00</div> 2, 4, 6, 8, 10, 12, 14, 16 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "ИНФОРМ КСиТ 2"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1216/0 (усл) ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "ул.Ломоносова, д.9, лит. М"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = "Информатика (Лек) : Актовый зал"

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>11:30-13:00</div> 2, 4, 6, 8, 10, 12, 14, 16 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "ИНФОРМ СиППО 1"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1216/0 (усл) ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "ул.Ломоносова, д.9, лит. М"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = "Информатика (Лек) : Актовый зал"

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

[[h4]]
class = "rasp_day_mobile"
text = "Суббота"

[[div]]
class = "rasp_tabl_day"

  [div.table]
  id = "6day"
  class = "rasp_tabl"
  border = "0"
  cellpadding = "0"
  cellspacing = "0"

    [div.table.tbody]
      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"
          [div.table.tbody.tr.th.span]
          text = "Сб"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>8:10-9:40</div> 6, 7, 10, 11, 12, 13, 14, 15 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "PRLCOMP 1"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1333 ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "Кронверкский пр., д.49, лит.А"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = " Parallel Computing / Параллельные вычисления (Лек) "

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>9:50-11:20</div> 6, 7, 10, 11, 12, 13, 14, 15 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "PRLCOMP 1.1"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1333 ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "Кронверкский пр., д.49, лит.А"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = " Parallel Computing / Параллельные вычисления (Лаб) "

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>11:30-13:00</div> 2, 4, 6, 8, 10, 12, 14, 16 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "ИНФОРМ (Р3106) 1.1"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1333 ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "Кронверкский пр., д.49, лит.А"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = "Информатика (Лаб)"

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>11:30-13:00</div> 3, 5, 7, 9, 11, 13, 15, 17 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "ИНФОРМ (Р3107) 1.2"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1333 ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "Кронверкский пр., д.49, лит.А"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = "Информатика (Лаб)"

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>13:30-15:00</div> 2, 4, 6, 8, 10, 12, 14, 16 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "ИНФОРМ (Р3106) 1.1"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1333 ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "Кронверкский пр., д.49, лит.А"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = "Информатика (Лаб)"

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"

      [[div.table.tbody.tr]]
        [div.table.tbody.tr.th]
        class = "day"

        [[div.table.tbody.tr.td]]
        class = "time"
          [div.table.tbody.tr.td.span]
          text = " <div>13:30-15:00</div> 3, 5, 7, 9, 11, 13, 15, 17 "

        [[div.table.tbody.tr.td]]
          [div.table.tbody.tr.td.span]
          text = "ИНФОРМ (Р3107) 1.2"

        [[div.table.tbody.tr.td]]
        class = "room"
          [div.table.tbody.tr.td.dl.dd]
          text = "1333 ауд."
          [div.table.tbody.tr.td.dl.dt]
            [div.table.tbody.tr.td.dl.dt.i]
            class = "fa fa-map-marker"
            [div.table.tbody.tr.td.dl.dt.span]
            text = "Кронверкский пр., д.49, лит.А"

        [[div.table.tbody.tr.td]]
        class = "lesson"
          [div.table.tbody.tr.td.dl.dd]
          text = "Информатика (Лаб)"

        [[div.table.tbody.tr.td]]
        class = "lesson-format"
        text = "Очно - дистанционный"
