[[day_1]]
name = "Понедельник"

  [[day_1.lesson_1]]
  time_range = "11:30-13:00"
  weeks = "2, 4, 6, 8, 10, 12, 14, 16"
  short_subject = "ИНФОРМ КСиТ 2"
  room_number = "1216/0 (усл) ауд."
  address = "ул.Ломоносова, д.9, лит. М"
  full_subject = "Информатика (Лек) : Актовый зал"
  format = "Очно - дистанционный"

  [[day_1.lesson_2]]
  time_range = "11:30-13:00"
  weeks = "2, 4, 6, 8, 10, 12, 14, 16"
  short_subject = "ИНФОРМ СиППО 1"
  room_number = "1216/0 (усл) ауд."
  address = "ул.Ломоносова, д.9, лит. М"
  full_subject = "Информатика (Лек) : Актовый зал"
  format = "Очно - дистанционный"

[[day_2]]
name = "Суббота"

  [[day_2.lesson_1]]
  time_range = "8:10-9:40"
  weeks = "6, 7, 10, 11, 12, 13, 14, 15"
  short_subject = "PRLCOMP 1"
  room_number = "1333 ауд."
  address = "Кронверкский пр., д.49, лит.А"
  full_subject = "Parallel Computing / Параллельные вычисления (Лек)"
  format = "Очно - дистанционный"

  [[day_2.lesson_2]]
  time_range = "9:50-11:20"
  weeks = "6, 7, 10, 11, 12, 13, 14, 15"
  short_subject = "PRLCOMP 1.1"
  room_number = "1333 ауд."
  address = "Кронверкский пр., д.49, лит.А"
  full_subject = "Parallel Computing / Параллельные вычисления (Лаб)"
  format = "Очно - дистанционный"

  [[day_2.lesson_3]]
  time_range = "11:30-13:00"
  weeks = "2, 4, 6, 8, 10, 12, 14, 16"
  short_subject = "ИНФОРМ (Р3106) 1.1"
  room_number = "1333 ауд."
  address = "Кронверкский пр., д.49, лит.А"
  full_subject = "Информатика (Лаб)"
  format = "Очно - дистанционный"

  [[day_2.lesson_4]]
  time_range = "11:30-13:00"
  weeks = "3, 5, 7, 9, 11, 13, 15, 17"
  short_subject = "ИНФОРМ (Р3107) 1.2"
  room_number = "1333 ауд."
  address = "Кронверкский пр., д.49, лит.А"
  full_subject = "Информатика (Лаб)"
  format = "Очно - дистанционный"

  [[day_2.lesson_5]]
  time_range = "13:30-15:00"
  weeks = "2, 4, 6, 8, 10, 12, 14, 16"
  short_subject = "ИНФОРМ (Р3106) 1.1"
  room_number = "1333 ауд."
  address = "Кронверкский пр., д.49, лит.А"
  full_subject = "Информатика (Лаб)"
  format = "Очно - дистанционный"

  [[day_2.lesson_6]]
  time_range = "13:30-15:00"
  weeks = "3, 5, 7, 9, 11, 13, 15, 17"
  short_subject = "ИНФОРМ (Р3107) 1.2"
  room_number = "1333 ауд."
  address = "Кронверкский пр., д.49, лит.А"
  full_subject = "Информатика (Лаб)"
  format = "Очно - дистанционный"
